//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoice_id { get; set; }
        public int booking_id { get; set; }
        public int booking_service_id { get; set; }
        public decimal total_amount { get; set; }
        public string payment_status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual BookingService BookingService { get; set; }
    }
}
